# Generated by Django 5.2.8 on 2025-11-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_detalleventa_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='subtotal',
            new_name='_subtotal',
        ),
    ]
