# Generated by Django 5.2.8 on 2025-11-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_subtotal_detalleventa__subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='_subtotal',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
