# Generated by Django 5.2.8 on 2025-11-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_detalleventa_precio_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
